config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit"

  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(tasks_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(tasks_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% @tasks.each do |task| %>

<li><%= link_to task.title, task_path(task) %></li><%= link_to "Delete",
            task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" },
            class: 'btn btn-danger' %>

<% end %>

<%= link_to 'Add a task', tasks_new_path, class: 'btn btn-primary' %>

app/views/tasks/new.html.erb
<h1>Form</h1>

<%= simple_form_for(@task) do |f| %>
 <%= f.input :title %>
  <%= f.input :details %>
<%= f.submit %>
<% end %>

<%= link_to 'Back to the list', tasks_path , class:'btn btn-primary'%>

app/views/tasks/show.html.erb
<h1> <%= @tasks.title %> </h1>
<h2> <%= @tasks.details %> </h2>

<% if @tasks.completed %>
<input type="checkbox"><h3>This Task is completed</h3>
<% else %>
<input type="checkbox"> <h3>This Task is not completed</h3>
<% end %>

<%= link_to 'Back to the list', tasks_path , class:'btn btn-primary'%>